"""Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number.
Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place,
they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull”.
Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes
throughout teh game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:

      >>> 1234
      2 cows, 0 bulls
      >>> 1286
      1 cow, 1 bull
      ...

    Until the user guesses the number."""

from random import randint

x = str(randint(1000, 9999))
counter: int = 0
guess: str = ''

print('Witamy w grze Mastermind!')
print('Odgadnij czterocyfrową liczbę!')

while guess != x:

    guess: str = input('Wprowadź liczbę:\n'
                       '>>> ')

    if len(guess) != 4:
        print('Należy wprowadzić czterocyfrową liczbę, powtórz próbę.')
        continue

    counter += 1

    in_place: int = 0
    in_x: int = 0

    supp_list: list = []
    x_list: list = list(x[:])

    for i, j in enumerate(guess):
        if guess[i] == x[i]:
            in_place += 1
            x_list.remove(guess[i])
            supp_list.append(guess[i])

    for i, j in enumerate(guess):
        if guess[i] in x_list and guess[i] not in supp_list:
            in_x += 1
            x_list.remove(guess[i])

    if x == guess:
        pass
    else:
        if in_place == 0 and in_x == 0:
            print('Żadna z cyfr nie znajduje się w liczbie.')
        else:
            print(f'Cyfry we właściwym miejscu: {in_place}, cyfry w niewłaściwym miejscu/miejscach: {in_x}')
else:
    print(f'Gratulacje! Odgadłeś liczbę {x} za {counter}. razem!')
