'''Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:

      >>> 1234
      2 cows, 0 bulls
      >>> 1286
      1 cow, 1 bull
      ...

    Until the user guesses the number.'''

from random import randint

x = str(randint(1000, 9999))
counter = 0
guess = ''
print(x)

print('Witamy w grze Mastermind!')
print('Odgadnij czterocyfrową liczbę!')

while guess != x:
    supporting_list_in_x = []
    supporting_list_in_place = []
    in_place = 0
    counter += 1
    guess = input('Wprowadź liczbę:\n'
                  '>>> ')

    for i, j in enumerate(guess):
        if j == x[i]:
            supporting_list_in_place.append(j)
            in_place += 1
        else:
            if j in x:
                supporting_list_in_x.append(j)

    for i, j in enumerate(supporting_list_in_x[::-1]):
        if j in supporting_list_in_place:
            supporting_list_in_x.remove(j)

    in_x = len(supporting_list_in_x)

    if in_place == 0 and in_x == 0:
        print('Żadna z cyfr nie znajduje się w liczbie.')
    else:
        if guess == x:
            pass
        else:
            print(f'Cyfry we właściwym miejscu: {in_place}, cyfry w niewłaściwym miejscu: {in_x}')
else:
    print(f'Gratulacje! Odgadłeś liczbę {x} za {counter}. razem!')
